FIRST_ENTRY_DIR = 'RPi'
RESOURCES_DIR = 'resources'
RESOURCES_PATH = f'{FIRST_ENTRY_DIR}/{RESOURCES_DIR}'

SERVER_CONFIG_PATH = f'{RESOURCES_PATH}/server_config.json'
DEVICES_CONFIGURATION_PATH = f'{RESOURCES_PATH}/devices_configuration.json'

# config.ini
CONFIG_PATH = f'{RESOURCES_PATH}/config.ini'

CENTRAL_UNIT_SECTION = 'central unit'
CENTRAL_UNIT_RUN_CENTRAL_UNIT = 'run_fake_central_unit'

CONNECTION_SECTION = 'connection'
CONNECTION_SECTION_IP_ADDRESS = 'ip_address'
CONNECTION_SECTION_PORT = 'port'